version: '3.8'

services:
  crm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    image: platform:v1
    container_name: Platform  # Set the container name to "Crm"

