name: Deploy platform

on:
  pull_request:
    branches:
      - dev  
  push:
    branches:
      - dev  
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Switch to root user
            sudo -i

            # Check if the repository exists, if not clone the dev branch directly
            if [ ! -d "/root/ding-ding-platform-nextjs" ]; then
              echo "Repository not found, cloning dev branch..."
              git clone -b dev git@github.com:Prathm0025/ding-ding-platform-nextjs.git
            else
              echo "Repository found, pulling latest changes from dev branch..."
              cd /root/ding-ding-platform-nextjs
              git checkout dev
              git pull origin dev
            fi

            # Navigate to the project directory
            cd /root/ding-ding-platform-nextjs

            # Build the new Docker image without stopping the running containers
            docker-compose build

            # After the image is built, stop the existing containers and immediately start the new ones
            docker-compose down
            docker-compose up -d

            # Clean up unused Docker images and containers
            docker image prune -f
          EOF
